import "@/app/globals.css";
import type { Metadata } from "next";
import { SWRProvider } from "@/utils/libs/swr/SWRProvider";
import { Footer } from "@/utils/ui/structure/Footer";
import { Header } from "@/utils/ui/structure/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="mx-auto flex min-h-dvh w-auto flex-col">
        <SWRProvider>
          <Header />
          {children}
          <Footer />
        </SWRProvider>
      </body>
    </html>
  );
}
